# Generated by Django 3.0.5 on 2020-05-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200502_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='videos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
